name: threeSD-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["linux-clang-format", "linux-fresh", "linux-mingw"]
    container: citraemu/build-environments:${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt5 (Linux)
        run: sudo apt-get update && sudo apt-get install -y qt5-default
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.image }}-
      - name: Query tag name
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
      - name: Build
        run: ./.ci/${{ matrix.image }}/docker.sh
      - name: Pack
        run: ./.ci/${{ matrix.image }}/upload.sh
        if: ${{ matrix.image != 'linux-clang-format' }}
        env:
          NAME: ${{ matrix.image }}
      - name: Upload
        uses: actions/upload-artifact@v2
        if: ${{ matrix.image != 'linux-mingw' && matrix.image != 'linux-clang-format' }}
        with:
          name: ${{ matrix.image }}
          path: artifacts/

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt5 (macOS)
        run: brew install qt@5
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/ccache
          key: ${{ runner.os }}-macos-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-macos-
      - name: Query tag name
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
      - name: Install dependencies
        run: ./.ci/macos/deps.sh
      - name: Build
        run: ./.ci/macos/build.sh
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"
      - name: Pack
        run: ./.ci/macos/upload.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: artifacts/

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt5 (Windows)
        run: |
          choco install qt5 -y --accept-license
          echo "C:\Qt\5.15.2\msvc2019_64\bin" >> $env:GITHUB_PATH
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.buildcache
          key: ${{ runner.os }}-win-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-win-
      - name: Install dependencies
        run: ./.ci/windows-msvc/deps.sh
        shell: bash
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: ./.ci/windows-msvc/build.sh
        shell: bash
        env:
          ENABLE_COMPATIBILITY_REPORTING: "ON"
